<a href="https://colab.research.google.com/github/amalsalilan/IPL_Infographics_Data_Analytics_-_Data_Visualization_Infosys_Internship_Oct2024/blob/K_Akshya/delivery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import os

In [ ]:
print(os.listdir())         #check weather the file is exist or not

['.config', 'deliveries.csv', 'sample_data']

In [ ]:
df=pd.read_csv("/content/deliveries.csv")
copy_data=df.copy()
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [ ]:
df.head(10)     #To get the first 10 lines of the dataset

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

In [ ]:
df.tail()        #to get last 5 lines of the dataset

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [ ]:
df.shape         #to get the rows and column

(260920, 17)

In [ ]:
df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
df.isnull().sum()        #To get the null values in the datase

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [ ]:
df.sample(10)           #to get the random 10 values

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
3288,335995,2,Kings XI Punjab,Delhi Daredevils,19,3,Yuvraj Singh,Shoaib Malik,B Lee,4,0,4,NaN,0,NaN,NaN,NaN
156151,1136585,1,Sunrisers Hyderabad,Kings XI Punjab,2,6,MK Pandey,AS Rajpoot,WP Saha,0,0,0,NaN,0,NaN,NaN,NaN
245751,1422126,2,Mumbai Indians,Sunrisers Hyderabad,9,4,Tilak Varma,Shahbaz Ahmed,Naman Dhir,2,0,2,NaN,0,NaN,NaN,NaN
173571,1178412,1,Kings XI Punjab,Delhi Capitals,14,6,Mandeep Singh,S Lamichhane,R Ashwin,1,0,1,NaN,0,NaN,NaN,NaN
137085,1082592,2,Rising Pune Supergiant,Mumbai Indians,18,4,MS Dhoni,JJ Bumrah,SPD Smith,0,0,0,NaN,0,NaN,NaN,NaN
77358,598002,1,Mumbai Indians,Chennai Super Kings,2,3,KD Karthik,DP Nannes,RT Ponting,1,0,1,NaN,0,NaN,NaN,NaN
106586,734031,1,Mumbai Indians,Delhi Daredevils,11,4,RG Sharma,S Nadeem,MEK Hussey,1,0,1,NaN,0,NaN,NaN,NaN
65406,548334,2,Kings XI Punjab,Mumbai Indians,8,6,Mandeep Singh,KA Pollard,SE Marsh,0,0,0,NaN,1,Mandeep Singh,caught,JEC Franklin
202873,1254096,2,Kolkata Knight Riders,Mumbai Indians,7,5,VR Iyer,RD Chahar,RA Tripathi,4,0,4,NaN,0,NaN,NaN,NaN
216613,1304082,1,Royal Challengers Bangalore,Sunrisers Hyderabad,6,7,SS Prabhudessai,J Suchith,Shahbaz Ahmed,3,0,3,NaN,0,NaN,NaN,NaN

In [ ]:
df.describe()              #It describes about the dataset

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,260920.0,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,335982.0,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,0.0,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,335982.0,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,335982.0,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,335982.0,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,335982.0,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,335982.0,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [ ]:
df.info()                      #it give info about dataset for example datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   match_id      260920 non-null  int64
 1   inning        260920 non-null  int64
 2   batting_team  260920 non-null  object
 3   bowling_team  260920 non-null  object
 4   over          260920 non-null  int64
 5   ball          260920 non-null  int64
 6   batter        260920 non-null  object
 7   bowler        260920 non-null  object
 8   non_striker   260920 non-null  object
 9   batsman_runs  260920 non-null  int64
 10  extra_runs    260920 non-null  int64
 11  total_runs    260920 non-null  int64
 12  is_wicket     260920 non-null  int64
dtypes: int64(8), object(5)
memory usage: 25.9+ MB

# **Detecting Null Values**

In [ ]:
missing_values=["N/a","na","NAN",np.nan]
df=pd.read_csv("/content/deliveries.csv",na_values=missing_values)

In [ ]:
df.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

# **Remove Null Values**

In [ ]:
# df.fillna()  # to remove the null row completely
# df.fillna(0) #to update the null valuesto 0
# df.fillna(how="all")  #to remove null value only all value in row is null
# df.fillna(method="ffill")   #to upadte forward value
# df.fillna(method="bfill")    #to update backward value
# df.interpolate()             #to fill the average value of top and bottom values

In [ ]:
df.drop(["fielder", "player_dismissed","dismissal_kind","extras_type"], axis=1, inplace=True, errors='ignore')
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0

In [ ]:
copy_data=df
copy_data

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0

# **loc & iloc**

In [ ]:
df.loc[(df['match_id'] == 335982) & (df['batting_team'] == 'Kolkata Knight Riders')]         #The loc function is used for label-based indexing

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,is_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,335982,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0
260916,335982,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0
260917,335982,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0
260918,335982,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0
260919,335982,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0

In [ ]:
df.iloc[:,0]                      #Helps to print the integer-location based indexing

0         335982
1         335982
2         335982
3         335982
4         335982
           ...
260915    335982
260916    335982
260917    335982
260918    335982
260919    335982
Name: match_id, Length: 260920, dtype: int64

# **Pivot Table**

In [ ]:
pd.pivot_table(df,index="batting_team",aggfunc='count')

,ball,batsman_runs,batter,bowler,bowling_team,extra_runs,inning,is_wicket,match_id,non_striker,over,total_runs
batting_team,,,,,,,,,,,,
Chennai Super Kings,28651,28651,28651,28651,28651,28651,28651,28651,28651,28651,28651,28651
Deccan Chargers,9034,9034,9034,9034,9034,9034,9034,9034,9034,9034,9034,9034
Delhi Capitals,10946,10946,10946,10946,10946,10946,10946,10946,10946,10946,10946,10946
Delhi Daredevils,18786,18786,18786,18786,18786,18786,18786,18786,18786,18786,18786,18786
Gujarat Lions,3566,3566,3566,3566,3566,3566,3566,3566,3566,3566,3566,3566
Gujarat Titans,5494,5494,5494,5494,5494,5494,5494,5494,5494,5494,5494,5494
Kings XI Punjab,22646,22646,22646,22646,22646,22646,22646,22646,22646,22646,22646,22646
Kochi Tuskers Kerala,1582,1582,1582,1582,1582,1582,1582,1582,1582,1582,1582,1582
Kolkata Knight Riders,29514,29514,29514,29514,29514,29514,29514,29514,29514,29514,29514,29514
Lucknow Super Giants,5400,5400,5400,5400,5400,5400,5400,5400,5400,5400,5400,5400
Mumbai Indians,31437,31437,31437,31437,31437,31437,31437,31437,31437,31437,31437,31437
Pune Warriors,5443,5443,5443,5443,5443,5443,5443,5443,5443,5443,5443,5443
Punjab Kings,6833,6833,6833,6833,6833,6833,6833,6833,6833,6833,6833,6833
Rajasthan Royals,26242,26242,26242,26242,26242,26242,26242,26242,26242,26242,26242,26242
Rising Pune Supergiant,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900,1900
Rising Pune Supergiants,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580
Royal Challengers Bangalore,28205,28205,28205,28205,28205,28205,28205,28205,28205,28205,28205,28205
Royal Challengers Bengaluru,1818,1818,1818,1818,1818,1818,1818,1818,1818,1818,1818,1818
Sunrisers Hyderabad,21843,21843,21843,21843,21843,21843,21843,21843,21843,21843,21843,21843

In [ ]:
max_runs_index = df['batsman_runs'].idxmax()  # Get the index of the maximum runs
max_runs = df['batsman_runs'].max()  # Get the maximum runs
team_name = df['batting_team'].iloc[max_runs_index]  # Get the team name at that index

print(f"Maximum Runs: {max_runs}, Team: {team_name}")

Maximum Runs: 6, Team: Kolkata Knight Riders