In [62]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df= pd.read_csv('all_season_details.csv')
df

C:\Users\govinda prasad\AppData\Local\Temp\ipykernel_19444\3647924527.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('all_season_details.csv')

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
0,110,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,1,481896,Mohammed Shami,0.1,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"nice and full, angling and perhaps swinging in...",<p><strong>7.30pm</strong> Gaikwad and Conway ...,NaN
1,120,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,1,"Mohammed Shami to Conway, 1 leg bye",False,False,False,379140,Devon Conway,0,2,481896,Mohammed Shami,0.2,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"Conway shuffles across off, and shimmies out a...",NaN,NaN
2,130,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,0,"Mohammed Shami to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,0,1,481896,Mohammed Shami,0.3,0,0,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"good length, angling in at off and then straig...",NaN,NaN
3,140,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,1,2,481896,Mohammed Shami,0.4,0,1,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"shorter and slanting into middle and leg, Gaik...","<p>Rummy: ""Fast bowling options for CSK defini...",NaN
4,150,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,3,481896,Mohammed Shami,0.5,0,1,0,1060380,Ruturaj Gaikwad,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Shami hits a heavy length and brings this back...,"<p>LG: ""Watching out for Hangargekar. He was i...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,219020,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,2,0,"Balaji to Warne, no run",False,False,False,8166,Shane Warne,7,7,26829,Lakshmipathy Balaji,3.2,0,35,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,lovely! Balaji's bowled a yorker outside off s...,NaN,NaN
242546,219030,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,3,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,8,8,26829,Lakshmipathy Balaji,3.3,0,36,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne steps down the track and throws his bat ...,NaN,<p>6 off 3 balls.</p>
242547,219050,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,9,9,26829,Lakshmipathy Balaji,3.4,0,39,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne reaches out for a full ball and squeezes...,NaN,<p>Three to win off two balls.</p>
242548,219040,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,2,"Balaji to Sohail Tanvir, 2 wides",False,True,False,43265,Sohail Tanvir,6,5,26829,Lakshmipathy Balaji,3.3,0,38,0,8166,Shane Warne,8,8,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,what has he done! Balaji has bowled a wide out...,<p>Rajasthan need two runs a ball. Balaji from...,NaN
242549,219060,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,5,2,"Balaji to Sohail Tanvir, 2 runs",False,False,False,43265,Sohail Tanvir,8,6,26829,Lakshmipathy Balaji,3.5,0,41,0,8166,Shane Warne,9,9,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Balaji bowls a full toss angling into the left...,NaN,<p>Rajasthan need one off the final ball.</p>

In [68]:
pd.set_option('display.max_columns',None)
df

,comment_id,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt,text,preText,postText
0,110,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,1,481896,Mohammed Shami,0.1,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"nice and full, angling and perhaps swinging in...",<p><strong>7.30pm</strong> Gaikwad and Conway ...,NaN
1,120,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,1,"Mohammed Shami to Conway, 1 leg bye",False,False,False,379140,Devon Conway,0,2,481896,Mohammed Shami,0.2,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"Conway shuffles across off, and shimmies out a...",NaN,NaN
2,130,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,0,"Mohammed Shami to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,0,1,481896,Mohammed Shami,0.3,0,0,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"good length, angling in at off and then straig...",NaN,NaN
3,140,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,1,2,481896,Mohammed Shami,0.4,0,1,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,"shorter and slanting into middle and leg, Gaik...","<p>Rummy: ""Fast bowling options for CSK defini...",NaN
4,150,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,3,481896,Mohammed Shami,0.5,0,1,0,1060380,Ruturaj Gaikwad,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,Shami hits a heavy length and brings this back...,"<p>LG: ""Watching out for Hangargekar. He was i...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,219020,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,2,0,"Balaji to Warne, no run",False,False,False,8166,Shane Warne,7,7,26829,Lakshmipathy Balaji,3.2,0,35,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,lovely! Balaji's bowled a yorker outside off s...,NaN,NaN
242546,219030,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,3,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,8,8,26829,Lakshmipathy Balaji,3.3,0,36,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne steps down the track and throws his bat ...,NaN,<p>6 off 3 balls.</p>
242547,219050,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,9,9,26829,Lakshmipathy Balaji,3.4,0,39,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Warne reaches out for a full ball and squeezes...,NaN,<p>Three to win off two balls.</p>
242548,219040,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,2,"Balaji to Sohail Tanvir, 2 wides",False,True,False,43265,Sohail Tanvir,6,5,26829,Lakshmipathy Balaji,3.3,0,38,0,8166,Shane Warne,8,8,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,what has he done! Balaji has bowled a wide out...,<p>Rajasthan need two runs a ball. Balaji from...,NaN
242549,219060,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,5,2,"Balaji to Sohail Tanvir, 2 runs",False,False,False,43265,Sohail Tanvir,8,6,26829,Lakshmipathy Balaji,3.5,0,41,0,8166,Shane Warne,9,9,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False,Balaji bowls a full toss angling into the left...,NaN,<p>Rajasthan need one off the final ball.</p>

In [70]:
df.shape

(242550, 45)

In [72]:
df.columns

Index(['comment_id', 'season', 'match_id', 'match_name', 'home_team',
       'away_team', 'current_innings', 'innings_id', 'over', 'ball', 'runs',
       'shortText', 'isBoundary', 'isWide', 'isNoball', 'batsman1_id',
       'batsman1_name', 'batsman1_runs', 'batsman1_balls', 'bowler1_id',
       'bowler1_name', 'bowler1_overs', 'bowler1_maidens', 'bowler1_runs',
       'bowler1_wkts', 'batsman2_id', 'batsman2_name', 'batsman2_runs',
       'batsman2_balls', 'bowler2_id', 'bowler2_name', 'bowler2_overs',
       'bowler2_maidens', 'bowler2_runs', 'bowler2_wkts', 'wicket_id',
       'wkt_batsman_name', 'wkt_bowler_name', 'wkt_batsman_runs',
       'wkt_batsman_balls', 'wkt_text', 'isRetiredHurt', 'text', 'preText',
       'postText'],
      dtype='object')

In [74]:
df.drop(['comment_id','text','preText','postText'],axis=1,inplace=True)
df

,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt
0,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,1,481896,Mohammed Shami,0.1,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,1,"Mohammed Shami to Conway, 1 leg bye",False,False,False,379140,Devon Conway,0,2,481896,Mohammed Shami,0.2,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,0,"Mohammed Shami to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,0,1,481896,Mohammed Shami,0.3,0,0,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,1,2,481896,Mohammed Shami,0.4,0,1,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,3,481896,Mohammed Shami,0.5,0,1,0,1060380,Ruturaj Gaikwad,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,2,0,"Balaji to Warne, no run",False,False,False,8166,Shane Warne,7,7,26829,Lakshmipathy Balaji,3.2,0,35,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
242546,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,3,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,8,8,26829,Lakshmipathy Balaji,3.3,0,36,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
242547,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,1,"Balaji to Warne, 1 run",False,False,False,8166,Shane Warne,9,9,26829,Lakshmipathy Balaji,3.4,0,39,0,43265,Sohail Tanvir,6,5,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
242548,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,4,2,"Balaji to Sohail Tanvir, 2 wides",False,True,False,43265,Sohail Tanvir,6,5,26829,Lakshmipathy Balaji,3.3,0,38,0,8166,Shane Warne,8,8,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
242549,2008.0,336040,CSK v RR,CSK,RR,RR,2,20,5,2,"Balaji to Sohail Tanvir, 2 runs",False,False,False,43265,Sohail Tanvir,8,6,26829,Lakshmipathy Balaji,3.5,0,41,0,8166,Shane Warne,9,9,46592.0,Makhaya Ntini,4.0,1.0,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False

In [76]:
df.head(50)

,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt
0,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,1,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,1,481896,Mohammed Shami,0.1,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,2,1,"Mohammed Shami to Conway, 1 leg bye",False,False,False,379140,Devon Conway,0,2,481896,Mohammed Shami,0.2,0,0,0,1060380,Ruturaj Gaikwad,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,3,0,"Mohammed Shami to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,0,1,481896,Mohammed Shami,0.3,0,0,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,4,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,1,2,481896,Mohammed Shami,0.4,0,1,0,379140,Devon Conway,0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,5,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,3,481896,Mohammed Shami,0.5,0,1,0,1060380,Ruturaj Gaikwad,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,1,6,0,"Mohammed Shami to Conway, no run",False,False,False,379140,Devon Conway,0,4,481896,Mohammed Shami,1.0,0,1,0,1060380,Ruturaj Gaikwad,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
6,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,1,4,"Pandya to Gaikwad, FOUR",True,False,False,1060380,Ruturaj Gaikwad,5,3,625371,Hardik Pandya,0.1,0,4,0,379140,Devon Conway,0,4,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
7,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,2,0,"Pandya to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,5,4,625371,Hardik Pandya,0.2,0,4,0,379140,Devon Conway,0,4,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
8,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,3,4,"Pandya to Gaikwad, FOUR",True,False,False,1060380,Ruturaj Gaikwad,9,5,625371,Hardik Pandya,0.3,0,8,0,379140,Devon Conway,0,4,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
9,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,4,1,"Pandya to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,10,6,625371,Hardik Pandya,0.4,0,9,0,379140,Devon Conway,0,4,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
10,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,5,1,"Pandya to Conway, 1 run",False,False,False,379140,Devon Conway,1,5,625371,Hardik Pandya,0.5,0,10,0,1060380,Ruturaj Gaikwad,10,6,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
11,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,2,6,1,"Pandya to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,11,7,625371,Hardik Pandya,1.0,0,11,0,379140,Devon Conway,1,5,481896.0,Mohammed Shami,1.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
12,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,1,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,12,8,481896,Mohammed Shami,1.1,0,2,0,379140,Devon Conway,1,5,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
13,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,2,0,"Mohammed Shami to Conway, OUT",False,False,False,379140,Devon Conway,1,6,481896,Mohammed Shami,1.2,0,2,1,1060380,Ruturaj Gaikwad,12,8,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,379140.0,Devon Conway,Mohammed Shami,1.0,6.0,DP Conway b Mohammed Shami 1 (6b 0x4 0x6) SR:...,False
14,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,3,0,"Mohammed Shami to Ali, no run",False,False,False,8917,Moeen Ali,0,1,481896,Mohammed Shami,1.3,0,2,1,1060380,Ruturaj Gaikwad,12,8,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
15,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,4,0,"Mohammed Shami to Ali, no run",False,False,False,8917,Moeen Ali,0,2,481896,Mohammed Shami,1.4,0,2,1,1060380,Ruturaj Gaikwad,12,8,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
16,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,5,0,"Mohammed Shami to Ali, no run",False,False,False,8917,Moeen Ali,0,3,481896,Mohammed Shami,1.5,0,2,1,1060380,Ruturaj Gaikwad,12,8,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
17,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,3,6,0,"Mohammed Shami to Ali, no run",False,False,False,8917,Moeen Ali,0,4,481896,Mohammed Shami,2.0,0,2,1,1060380,Ruturaj Gaikwad,12,8,625371.0,Hardik Pandya,1.0,0.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
18,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,1,6,"Little to Gaikwad, SIX",True,False,False,1060380,Ruturaj Gaikwad,18,9,928067,Josh Little,0.1,0,6,0,8917,Moeen Ali,0,4,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
19,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,2,4,"Little to Gaikwad, FOUR",True,False,False,1060380,Ruturaj Gaikwad,22,10,928067,Josh Little,0.2,0,10,0,8917,Moeen Ali,0,4,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
20,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,3,1,"Little to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,23,11,928067,Josh Little,0.3,0,11,0,8917,Moeen Ali,0,4,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
21,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,4,0,"Little to Ali, no run",False,False,False,8917,Moeen Ali,0,5,928067,Josh Little,0.4,0,11,0,1060380,Ruturaj Gaikwad,23,11,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
22,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,5,4,"Little to Ali, FOUR",True,False,False,8917,Moeen Ali,4,6,928067,Josh Little,0.5,0,15,0,1060380,Ruturaj Gaikwad,23,11,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
23,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,4,6,0,"Little to Ali, no run",False,False,False,8917,Moeen Ali,4,7,928067,Josh Little,1.0,0,15,0,1060380,Ruturaj Gaikwad,23,11,481896.0,Mohammed Shami,2.0,0.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
24,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,1,0,"Mohammed Shami to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,23,12,481896,Mohammed Shami,2.1,0,2,1,8917,Moeen Ali,4,7,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
25,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,2,1,"Mohammed Shami to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,24,13,481896,Mohammed Shami,2.2,0,3,1,8917,Moeen Ali,4,7,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
26,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,3,4,"Mohammed Shami to Ali, FOUR",True,False,False,8917,Moeen Ali,8,8,481896,Mohammed Shami,2.3,0,7,1,1060380,Ruturaj Gaikwad,24,13,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
27,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,4,6,"Mohammed Shami to Ali, SIX",True,False,False,8917,Moeen Ali,14,10,481896,Mohammed Shami,2.4,0,14,1,1060380,Ruturaj Gaikwad,24,13,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
28,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,4,1,"Mohammed Shami to Ali, 1 no ball",False,False,True,8917,Moeen Ali,8,9,481896,Mohammed Shami,2.3,0,8,1,1060380,Ruturaj Gaikwad,24,13,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
29,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,5,4,"Mohammed Shami to Ali, FOUR",True,False,False,8917,Moeen Ali,18,11,481896,Mohammed Shami,2.5,0,18,1,1060380,Ruturaj Gaikwad,24,13,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
30,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,5,6,1,"Mohammed Shami to Ali, 1 run",False,False,False,8917,Moeen Ali,19,12,481896,Mohammed Shami,3.0,0,19,1,1060380,Ruturaj Gaikwad,24,13,928067.0,Josh Little,1.0,0.0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
31,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,1,0,"Rashid Khan to Ali, no run",False,False,False,8917,Moeen Ali,19,13,793463,Rashid Khan,0.1,0,0,0,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
32,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,2,0,"Rashid Khan to Ali, no run",False,False,False,8917,Moeen Ali,19,14,793463,Rashid Khan,0.2,0,0,0,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
33,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,3,0,"Rashid Khan to Ali, no run",False,False,False,8917,Moeen Ali,19,15,793463,Rashid Khan,0.3,0,0,0,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
34,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,4,4,"Rashid Khan to Ali, FOUR",True,False,False,8917,Moeen Ali,23,16,793463,Rashid Khan,0.4,0,4,0,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
35,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,5,0,"Rashid Khan to Ali, OUT",False,False,False,8917,Moeen Ali,23,17,793463,Rashid Khan,0.5,0,4,1,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,8917.0,Moeen Ali,Rashid Khan,23.0,17.0,MM Ali c &dagger;Saha b Rashid Khan 23 (17b 4x...,False
36,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,6,6,1,"Rashid Khan to Stokes, 1 run",False,False,False,311158,Ben Stokes,1,1,793463,Rashid Khan,1.0,0,5,1,1060380,Ruturaj Gaikwad,24,13,481896.0,Mohammed Shami,3.0,0.0,19.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
37,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,1,0,"Pandya to Stokes, no run",False,False,False,311158,Ben Stokes,1,2,625371,Hardik Pandya,1.1,0,11,0,1060380,Ruturaj Gaikwad,24,13,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
38,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,2,1,"Pandya to Stokes, 1 run",False,False,False,311158,Ben Stokes,2,3,625371,Hardik Pandya,1.2,0,12,0,1060380,Ruturaj Gaikwad,24,13,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
39,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,3,6,"Pandya to Gaikwad, SIX",True,False,False,1060380,Ruturaj Gaikwad,30,14,625371,Hardik Pandya,1.3,0,18,0,311158,Ben Stokes,2,3,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
40,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,4,6,"Pandya to Gaikwad, SIX",True,False,False,1060380,Ruturaj Gaikwad,36,15,625371,Hardik Pandya,1.4,0,24,0,311158,Ben Stokes,2,3,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
41,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,5,0,"Pandya to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,36,16,625371,Hardik Pandya,1.5,0,24,0,311158,Ben Stokes,2,3,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
42,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,7,6,0,"Pandya to Gaikwad, no run",False,False,False,1060380,Ruturaj Gaikwad,36,17,625371,Hardik Pandya,2.0,0,24,0,311158,Ben Stokes,2,3,793463.0,Rashid Khan,1.0,0.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,False
43,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,1,1,"Rashid Khan to Stokes, 1 run",False,False,False,311158,Ben Stokes,3,4,793463,Rashid Khan,1.1,0,6,1,1060380,Ruturaj Gaikwad,36,17,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
44,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,2,1,"Rashid Khan to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,37,18,793463,Rashid Khan,1.2,0,7,1,311158,Ben Stokes,3,4,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
45,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,3,4,"Rashid Khan to Stokes, FOUR",True,False,False,311158,Ben Stokes,7,5,793463,Rashid Khan,1.3,0,11,1,1060380,Ruturaj Gaikwad,37,18,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
46,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,4,0,"Rashid Khan to Stokes, OUT",False,False,False,311158,Ben Stokes,7,6,793463,Rashid Khan,1.4,0,11,2,1060380,Ruturaj Gaikwad,37,18,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,311158.0,Ben Stokes,Rashid Khan,7.0,6.0,BA Stokes c &dagger;Saha b Rashid Khan 7 (6b 1...,False
47,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,5,1,"Rashid Khan to Rayudu, 1 run",False,False,False,33141,Ambati Rayudu,1,1,793463,Rashid Khan,1.5,0,12,2,1060380,Ruturaj Gaikwad,37,18,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
48,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,8,6,1,"Rashid Khan to Gaikwad, 1 run",False,False,False,1060380,Ruturaj Gaikwad,38,19,793463,Rashid Khan,2.0,0,13,2,33141,Ambati Rayudu,1,1,625371.0,Hardik Pandya,2.0,0.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,False
49,2023.0,1359475,GT v CSK,GT,CSK,CSK,1,9,1,6,"Joseph to Gaikwad, SIX",True,False,False,1060380,Ruturaj Gaikwad,44,20,670031,Alzarri Joseph,0.1,0,6,0,33141,Ambati Rayudu,1,1,793463.0,Rashid Khan,2.0,0.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,False

In [78]:
df.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team',
       'current_innings', 'innings_id', 'over', 'ball', 'runs', 'shortText',
       'isBoundary', 'isWide', 'isNoball', 'batsman1_id', 'batsman1_name',
       'batsman1_runs', 'batsman1_balls', 'bowler1_id', 'bowler1_name',
       'bowler1_overs', 'bowler1_maidens', 'bowler1_runs', 'bowler1_wkts',
       'batsman2_id', 'batsman2_name', 'batsman2_runs', 'batsman2_balls',
       'bowler2_id', 'bowler2_name', 'bowler2_overs', 'bowler2_maidens',
       'bowler2_runs', 'bowler2_wkts', 'wicket_id', 'wkt_batsman_name',
       'wkt_bowler_name', 'wkt_batsman_runs', 'wkt_batsman_balls', 'wkt_text',
       'isRetiredHurt'],
      dtype='object')

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242550 entries, 0 to 242549
Data columns (total 41 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   season             242067 non-null  float64
 1   match_id           242550 non-null  int64
 2   match_name         242550 non-null  object
 3   home_team          242550 non-null  object
 4   away_team          242550 non-null  object
 5   current_innings    242550 non-null  object
 6   innings_id         242550 non-null  int64
 7   over               242550 non-null  int64
 8   ball               242550 non-null  int64
 9   runs               242550 non-null  int64
 10  shortText          242550 non-null  object
 11  isBoundary         242550 non-null  bool
 12  isWide             242550 non-null  bool
 13  isNoball           242550 non-null  bool
 14  batsman1_id        242550 non-null  int64
 15  batsman1_name      242550 non-null  object
 16  batsman1_runs      242550 non-null  int64
 17  batsman1_balls     242550 non-null  int64
 18  bowler1_id         242550 non-null  int64
 19  bowler1_name       242550 non-null  object
 20  bowler1_overs      242550 non-null  float64
 21  bowler1_maidens    242550 non-null  int64
 22  bowler1_runs       242550 non-null  int64
 23  bowler1_wkts       242550 non-null  int64
 24  batsman2_id        242550 non-null  object
 25  batsman2_name      242548 non-null  object
 26  batsman2_runs      242550 non-null  int64
 27  batsman2_balls     242550 non-null  int64
 28  bowler2_id         229709 non-null  float64
 29  bowler2_name       229709 non-null  object
 30  bowler2_overs      229709 non-null  float64
 31  bowler2_maidens    229709 non-null  float64
 32  bowler2_runs       229709 non-null  float64
 33  bowler2_wkts       229709 non-null  float64
 34  wicket_id          11880 non-null   float64
 35  wkt_batsman_name   11880 non-null   object
 36  wkt_bowler_name    11880 non-null   object
 37  wkt_batsman_runs   11880 non-null   float64
 38  wkt_batsman_balls  11880 non-null   float64
 39  wkt_text           11880 non-null   object
 40  isRetiredHurt      242550 non-null  bool
dtypes: bool(4), float64(10), int64(14), object(13)
memory usage: 69.4+ MB

In [101]:
df.isnull().sum()

season                  483
match_id                  0
match_name                0
home_team                 0
away_team                 0
current_innings           0
innings_id                0
over                      0
ball                      0
runs                      0
shortText                 0
isBoundary                0
isWide                    0
isNoball                  0
batsman1_id               0
batsman1_name             0
batsman1_runs             0
batsman1_balls            0
bowler1_id                0
bowler1_name              0
bowler1_overs             0
bowler1_maidens           0
bowler1_runs              0
bowler1_wkts              0
batsman2_id               0
batsman2_name             2
batsman2_runs             0
batsman2_balls            0
bowler2_id            12841
bowler2_name          12841
bowler2_overs         12841
bowler2_maidens       12841
bowler2_runs          12841
bowler2_wkts          12841
wicket_id            230670
wkt_batsman_name     230670
wkt_bowler_name      230670
wkt_batsman_runs     230670
wkt_batsman_balls    230670
wkt_text             230670
isRetiredHurt             0
dtype: int64

In [109]:
df[df['season'].isnull()]

,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt
5080,NaN,1359496,MI v KKR,KKR,MI,KKR,1,1,1,0,"Tendulkar to Rahmanullah Gurbaz, no run",False,False,False,974087,Rahmanullah Gurbaz,0,1,1148776,Arjun Tendulkar,0.1,0,0,0,1048813,Narayan Jagadeesan,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5081,NaN,1359496,MI v KKR,KKR,MI,KKR,1,1,2,2,"Tendulkar to Rahmanullah Gurbaz, 2 runs",False,False,False,974087,Rahmanullah Gurbaz,2,2,1148776,Arjun Tendulkar,0.2,0,2,0,1048813,Narayan Jagadeesan,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5082,NaN,1359496,MI v KKR,KKR,MI,KKR,1,1,3,1,"Tendulkar to Rahmanullah Gurbaz, 1 run",False,False,False,974087,Rahmanullah Gurbaz,3,3,1148776,Arjun Tendulkar,0.3,0,3,0,1048813,Narayan Jagadeesan,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5083,NaN,1359496,MI v KKR,KKR,MI,KKR,1,1,4,1,"Tendulkar to Jagadeesan, 1 leg bye",False,False,False,1048813,Narayan Jagadeesan,0,1,1148776,Arjun Tendulkar,0.4,0,3,0,974087,Rahmanullah Gurbaz,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5084,NaN,1359496,MI v KKR,KKR,MI,KKR,1,1,5,0,"Tendulkar to Rahmanullah Gurbaz, no run",False,False,False,974087,Rahmanullah Gurbaz,3,4,1148776,Arjun Tendulkar,0.5,0,3,0,1048813,Narayan Jagadeesan,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15196,NaN,1359538,PBKS v DC,DC,PBKS,PBKS,2,20,3,4,"Sharma to Livingstone, FOUR",True,False,False,403902,Liam Livingstone,88,44,236779,Ishant Sharma,2.3,0,29,1,1064812,Rahul Chahar,0,0,481979.0,Anrich Nortje,4.0,0.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,False
15197,NaN,1359538,PBKS v DC,DC,PBKS,PBKS,2,20,4,0,"Sharma to Livingstone, no run",False,False,False,403902,Liam Livingstone,94,46,236779,Ishant Sharma,2.4,0,36,1,1064812,Rahul Chahar,0,0,481979.0,Anrich Nortje,4.0,0.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,False
15198,NaN,1359538,PBKS v DC,DC,PBKS,PBKS,2,20,4,7,"Sharma to Livingstone, (no ball) SIX",True,False,True,403902,Liam Livingstone,94,45,236779,Ishant Sharma,2.3,0,36,1,1064812,Rahul Chahar,0,0,481979.0,Anrich Nortje,4.0,0.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,False
15199,NaN,1359538,PBKS v DC,DC,PBKS,PBKS,2,20,5,0,"Sharma to Livingstone, no run",False,False,False,403902,Liam Livingstone,94,47,236779,Ishant Sharma,2.5,0,36,1,1064812,Rahul Chahar,0,0,481979.0,Anrich Nortje,4.0,0.0,36.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,False
15200,NaN,1359538,PBKS v DC,DC,PBKS,PBKS,2,20,6,0,"Sharma to Livingstone, OUT",False,False,False,403902,Liam Livingstone,94,48,236779,Ishant Sharma,3.0,0,36,2,1064812,Rahul Chahar,0,0,481979.0,Anrich Nortje,4.0,0.0,36.0,2.0,403902.0,Liam Livingstone,Ishant Sharma,94.0,48.0,LS Livingstone c Patel b Sharma 94 (69m 48b 5x...,False

In [119]:
    df.loc[(df['match_id'].isin([1359496,1359538])) & (df['season'].isnull()), 'season'] = 2023

In [121]:
df.isnull().sum()

season                    0
match_id                  0
match_name                0
home_team                 0
away_team                 0
current_innings           0
innings_id                0
over                      0
ball                      0
runs                      0
shortText                 0
isBoundary                0
isWide                    0
isNoball                  0
batsman1_id               0
batsman1_name             0
batsman1_runs             0
batsman1_balls            0
bowler1_id                0
bowler1_name              0
bowler1_overs             0
bowler1_maidens           0
bowler1_runs              0
bowler1_wkts              0
batsman2_id               0
batsman2_name             2
batsman2_runs             0
batsman2_balls            0
bowler2_id            12841
bowler2_name          12841
bowler2_overs         12841
bowler2_maidens       12841
bowler2_runs          12841
bowler2_wkts          12841
wicket_id            230670
wkt_batsman_name     230670
wkt_bowler_name      230670
wkt_batsman_runs     230670
wkt_batsman_balls    230670
wkt_text             230670
isRetiredHurt             0
dtype: int64

In [139]:
df.duplicated().sum()

np.int64(1)

In [141]:
df[df.duplicated()]

,season,match_id,match_name,home_team,away_team,current_innings,innings_id,over,ball,runs,shortText,isBoundary,isWide,isNoball,batsman1_id,batsman1_name,batsman1_runs,batsman1_balls,bowler1_id,bowler1_name,bowler1_overs,bowler1_maidens,bowler1_runs,bowler1_wkts,batsman2_id,batsman2_name,batsman2_runs,batsman2_balls,bowler2_id,bowler2_name,bowler2_overs,bowler2_maidens,bowler2_runs,bowler2_wkts,wicket_id,wkt_batsman_name,wkt_bowler_name,wkt_batsman_runs,wkt_batsman_balls,wkt_text,isRetiredHurt
13082,2023.0,1359530,KKR v RR,KKR,RR,KKR,1,1,1,2,"Boult to JJ Roy, 2 runs",False,False,False,298438,Jason Roy,2,1,277912,Trent Boult,0.1,0,2,0,974087,Rahmanullah Gurbaz,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [147]:
df.drop_duplicates(inplace=True)

In [149]:
df.duplicated().sum()

np.int64(0)

In [151]:
df.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team',
       'current_innings', 'innings_id', 'over', 'ball', 'runs', 'shortText',
       'isBoundary', 'isWide', 'isNoball', 'batsman1_id', 'batsman1_name',
       'batsman1_runs', 'batsman1_balls', 'bowler1_id', 'bowler1_name',
       'bowler1_overs', 'bowler1_maidens', 'bowler1_runs', 'bowler1_wkts',
       'batsman2_id', 'batsman2_name', 'batsman2_runs', 'batsman2_balls',
       'bowler2_id', 'bowler2_name', 'bowler2_overs', 'bowler2_maidens',
       'bowler2_runs', 'bowler2_wkts', 'wicket_id', 'wkt_batsman_name',
       'wkt_bowler_name', 'wkt_batsman_runs', 'wkt_batsman_balls', 'wkt_text',
       'isRetiredHurt'],
      dtype='object')

In [155]:
teams=df['home_team'].unique()
teams

array(['GT', 'PBKS', 'LSG', 'SRH', 'RCB', 'CSK', 'DC', 'RR', 'KKR', 'MI',
       'KXIP', 'RPS', 'GL', 'PWI', 'Kochi'], dtype=object)

In [179]:
df.groupby(['season'])['match_id'].nunique()

season
2008.0    58
2009.0    57
2010.0    60
2011.0    73
2012.0    74
2013.0    76
2014.0    60
2015.0    59
2016.0    60
2017.0    59
2018.0    60
2019.0    60
2020.0    60
2021.0    60
2022.0    74
2023.0    73
Name: match_id, dtype: int64

In [288]:
df.groupby(['season'])['match_id'].nunique().sum()

np.int64(1023)

In [264]:
df.groupby(['season'])['away_team'].nunique()

season
2008.0     8
2009.0     8
2010.0     8
2011.0    10
2012.0     9
2013.0     9
2014.0     8
2015.0     8
2016.0     8
2017.0     8
2018.0     8
2019.0     8
2020.0     8
2021.0     8
2022.0    10
2023.0    10
Name: away_team, dtype: int64

In [282]:
df['home_team'][df['season']==2009].unique()

array(['CSK', 'RCB', 'DC', 'SRH', 'KXIP', 'KKR', 'MI'], dtype=object)

In [284]:
df['away_team'][df['season']==2009].unique()

array(['MI', 'RR', 'KXIP', 'KKR', 'CSK', 'SRH', 'DC', 'RCB'], dtype=object)

In [304]:
df.groupby('home_team')['runs'].sum().sort_values(ascending=False).head(10)

home_team
CSK     38452
RCB     38285
DC      38057
MI      37828
SRH     37371
KKR     34903
RR      30118
KXIP    29635
PBKS     6577
PWI      6436
Name: runs, dtype: int64

In [310]:
df.groupby('home_team')['wicket_id'].count().sort_values(ascending=False).head(10)

home_team
SRH     1470
MI      1425
CSK     1417
RCB     1401
DC      1395
KKR     1334
RR      1084
KXIP    1036
PWI      270
PBKS     227
Name: wicket_id, dtype: int64

In [306]:
df.groupby('away_team')['runs'].sum().sort_values(ascending=False).head(10)

away_team
MI      39762
KKR     38011
SRH     37428
RCB     36958
DC      35545
RR      33992
CSK     31843
KXIP    30517
PBKS     7279
PWI      6739
Name: runs, dtype: int64

In [312]:
df.groupby('away_team')['wicket_id'].count().sort_values(ascending=False).head(10)

away_team
MI      1510
KKR     1395
DC      1393
SRH     1375
RCB     1351
RR      1285
KXIP    1161
CSK     1108
PBKS     272
PWI      261
Name: wicket_id, dtype: int64

In [318]:
df.groupby('batsman1_name')['runs'].sum().sort_values(ascending=False).head(10)

batsman1_name
Virat Kohli       7513
Shikhar Dhawan    6948
David Warner      6722
Rohit Sharma      6414
Suresh Raina      5762
AB de Villiers    5312
Chris Gayle       5296
MS Dhoni          5245
Robin Uthappa     5237
Dinesh Karthik    4692
Name: runs, dtype: int64

In [316]:
df.groupby('batsman2_name')['runs'].sum().sort_values(ascending=False).head(10)

batsman2_name
Virat Kohli       7857
Shikhar Dhawan    7814
Rohit Sharma      6425
David Warner      5829
Suresh Raina      5764
Ajinkya Rahane    5061
Gautam Gambhir    4948
MS Dhoni          4870
Robin Uthappa     4805
Dinesh Karthik    4675
Name: runs, dtype: int64

In [337]:
df.groupby('bowler1_name')['wicket_id'].count().sort_values(ascending=False).head(10)

bowler1_name
Dwayne Bravo           200
Yuzvendra Chahal       194
Piyush Chawla          188
Ravichandran Ashwin    188
Lasith Malinga         186
Amit Mishra            182
Bhuvneshwar Kumar      182
Sunil Narine           182
Harbhajan Singh        161
Ravindra Jadeja        160
Name: wicket_id, dtype: int64

In [339]:
df.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team',
       'current_innings', 'innings_id', 'over', 'ball', 'runs', 'shortText',
       'isBoundary', 'isWide', 'isNoball', 'batsman1_id', 'batsman1_name',
       'batsman1_runs', 'batsman1_balls', 'bowler1_id', 'bowler1_name',
       'bowler1_overs', 'bowler1_maidens', 'bowler1_runs', 'bowler1_wkts',
       'batsman2_id', 'batsman2_name', 'batsman2_runs', 'batsman2_balls',
       'bowler2_id', 'bowler2_name', 'bowler2_overs', 'bowler2_maidens',
       'bowler2_runs', 'bowler2_wkts', 'wicket_id', 'wkt_batsman_name',
       'wkt_bowler_name', 'wkt_batsman_runs', 'wkt_batsman_balls', 'wkt_text',
       'isRetiredHurt'],
      dtype='object')

In [354]:
df.groupby('bowler1_name')['isNoball'].sum().sort_values(ascending=False).head(10)

bowler1_name
Jasprit Bumrah     27
Umesh Yadav        24
Sreesanth          23
Ishant Sharma      22
Amit Mishra        21
Lasith Malinga     18
Prasidh Krishna    17
Ashok Dinda        14
Harshal Patel      14
Brett Lee          13
Name: isNoball, dtype: int64

In [356]:
df.groupby('bowler1_name')['isWide'].sum().sort_values(ascending=False).head(10)

bowler1_name
Dwayne Bravo           166
Ravichandran Ashwin    134
Lasith Malinga         127
Bhuvneshwar Kumar      123
Praveen Kumar          111
Umesh Yadav            106
Shardul Thakur          98
Shane Watson            95
Dale Steyn              93
Mohammed Siraj          89
Name: isWide, dtype: int64

In [362]:
df.groupby('bowler1_name')['isBoundary'].sum().sort_values(ascending=False).head(10)

bowler1_name
Umesh Yadav            581
Bhuvneshwar Kumar      570
Piyush Chawla          562
Dwayne Bravo           494
Mohammed Shami         484
Ravichandran Ashwin    472
Ravindra Jadeja        461
Sandeep Sharma         452
Praveen Kumar          441
Harbhajan Singh        441
Name: isBoundary, dtype: int64

In [364]:
df.groupby('batsman1_name')['isBoundary'].sum().sort_values(ascending=False).head(10)

batsman1_name
Shikhar Dhawan    896
Virat Kohli       876
David Warner      872
Rohit Sharma      808
Chris Gayle       760
Suresh Raina      708
Robin Uthappa     662
AB de Villiers    661
MS Dhoni          575
Dinesh Karthik    575
Name: isBoundary, dtype: int64

In [368]:
df.groupby('batsman1_name')['ball'].count().sort_values(ascending=False).head(10)

batsman1_name
Virat Kohli       5726
Shikhar Dhawan    5353
Rohit Sharma      4880
David Warner      4713
Suresh Raina      4170
Robin Uthappa     3921
MS Dhoni          3829
Ajinkya Rahane    3653
Gautam Gambhir    3524
Chris Gayle       3498
Name: ball, dtype: int64

In [374]:
df.groupby('batsman1_name')['isRetiredHurt'].sum().sort_values(ascending=False).head(10)

batsman1_name
Sachin Tendulkar    2
Shikhar Dhawan      2
Krunal Pandya       1
Aaron Finch         1
Kevin Pietersen     1
Dominic Thornely    1
Harbhajan Singh     1
Liam Livingstone    1
Jaskaran Singh      1
Ambati Rayudu       1
Name: isRetiredHurt, dtype: int64

In [382]:
df.columns

Index(['season', 'match_id', 'match_name', 'home_team', 'away_team',
       'current_innings', 'innings_id', 'over', 'ball', 'runs', 'shortText',
       'isBoundary', 'isWide', 'isNoball', 'batsman1_id', 'batsman1_name',
       'batsman1_runs', 'batsman1_balls', 'bowler1_id', 'bowler1_name',
       'bowler1_overs', 'bowler1_maidens', 'bowler1_runs', 'bowler1_wkts',
       'batsman2_id', 'batsman2_name', 'batsman2_runs', 'batsman2_balls',
       'bowler2_id', 'bowler2_name', 'bowler2_overs', 'bowler2_maidens',
       'bowler2_runs', 'bowler2_wkts', 'wicket_id', 'wkt_batsman_name',
       'wkt_bowler_name', 'wkt_batsman_runs', 'wkt_batsman_balls', 'wkt_text',
       'isRetiredHurt'],
      dtype='object')

In [394]:
df.groupby('wkt_batsman_name')['match_id'].count().sort_values(ascending=False).head(10)

wkt_batsman_name
Rohit Sharma      218
Virat Kohli       204
Shikhar Dhawan    189
Robin Uthappa     181
Dinesh Karthik    179
Suresh Raina      167
David Warner      154
Ambati Rayudu     152
MS Dhoni          143
Ajinkya Rahane    142
Name: match_id, dtype: int64

In [468]:
h=df[['match_id','batsman1_name','batsman1_runs']][df['batsman1_runs']>= 100]
h['batsman1_name'].nunique()

47

In [488]:

h=df[['match_id','batsman1_name','batsman1_runs']][df['batsman1_runs']>= 100]
h

        match_id     batsman1_name  batsman1_runs
4459     1359493       Harry Brook            100
5184     1359496    Venkatesh Iyer            100
5187     1359496    Venkatesh Iyer            104
5188     1359496    Venkatesh Iyer            104
10080    1359516  Yashasvi Jaiswal            100
...          ...               ...            ...
241732    336019       Shaun Marsh            110
241733    336019       Shaun Marsh            111
241735    336019       Shaun Marsh            115
241736    336019       Shaun Marsh            115
241737    336019       Shaun Marsh            115

[479 rows x 3 columns]

In [500]:
h.groupby(['match_id','batsman1_name'])['batsman1_runs'].max()

match_id  batsman1_name
335982    Brendon McCullum     158
335983    Michael Hussey       116
335990    Andrew Symonds       117
335994    Adam Gilchrist       109
336018    Sanath Jayasuriya    114
                              ...
1359539   Virat Kohli          100
1359543   Cameron Green        100
1359544   Shubman Gill         104
          Virat Kohli          101
1370352   Shubman Gill         129
Name: batsman1_runs, Length: 85, dtype: int64

In [528]:
a=h.groupby(['match_id','batsman1_name'])['batsman1_runs'].max().sort_values(ascending=False).reset_index()
a

    match_id     batsman1_name  batsman1_runs
0     598027       Chris Gayle            174
1     335982  Brendon McCullum            158
2    1304112   Quinton de Kock            140
3     829795    AB de Villiers            133
4    1216510          KL Rahul            132
..       ...               ...            ...
80   1178410       Virat Kohli            100
81   1304055       Jos Buttler            100
82   1359493       Harry Brook            100
83   1359539       Virat Kohli            100
84   1359543     Cameron Green            100

[85 rows x 3 columns]

In [532]:
a['batsman1_name'].value_counts()

batsman1_name
Virat Kohli           7
Chris Gayle           6
Jos Buttler           5
David Warner          4
Shane Watson          4
KL Rahul              4
Shubman Gill          3
Sanju Samson          3
AB de Villiers        3
Quinton de Kock       2
Virender Sehwag       2
Adam Gilchrist        2
Ajinkya Rahane        2
Shikhar Dhawan        2
Murali Vijay          2
Ben Stokes            2
Hashim Amla           2
Brendon McCullum      1
Rishabh Pant          1
Andrew Symonds        1
Paul Valthaty         1
Wriddhiman Saha       1
Michael Hussey        1
Manish Pandey         1
Sanath Jayasuriya     1
Jonny Bairstow        1
Shaun Marsh           1
Rohit Sharma          1
Mahela Jayawardene    1
Rajat Patidar         1
Yashasvi Jaiswal      1
Mayank Agarwal        1
Venkatesh Iyer        1
Heinrich Klaasen      1
Kevin Pietersen       1
Suryakumar Yadav      1
Prabhsimran Singh     1
Steven Smith          1
David Miller          1
Devdutt Padikkal      1
Ruturaj Gaikwad       1
Yusuf Pathan          1
Suresh Raina          1
Lendl Simmons         1
Ambati Rayudu         1
Harry Brook           1
Cameron Green         1
Name: count, dtype: int64