In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('sample_dataset.csv')

In [3]:
df

,Unnamed: 0,season,match_id,home_team,away_team,current_innings,over,ball,wkt_batsman_runs,isRetiredHurt,cumulative_runs,wickets_lost,overs_bowled,run_rate,powerplay
0,0,2023.0,1359475,GT,CSK,CSK,1,1,0.0,False,0.0,0,1.166667,0.000000,True
1,1,2023.0,1359475,GT,CSK,CSK,1,2,0.0,False,0.0,0,1.333333,0.000000,True
2,2,2023.0,1359475,GT,CSK,CSK,1,3,0.0,False,0.0,0,1.500000,0.000000,True
3,3,2023.0,1359475,GT,CSK,CSK,1,4,0.0,False,0.0,0,1.666667,0.000000,True
4,4,2023.0,1359475,GT,CSK,CSK,1,5,0.0,False,0.0,0,1.833333,0.000000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242545,242545,2008.0,336040,CSK,RR,RR,20,2,0.0,False,77.0,2,20.333333,3.786885,False
242546,242546,2008.0,336040,CSK,RR,RR,20,3,0.0,False,77.0,3,20.500000,3.756098,False
242547,242547,2008.0,336040,CSK,RR,RR,20,4,0.0,False,77.0,3,20.666667,3.725806,False
242548,242548,2008.0,336040,CSK,RR,RR,20,4,0.0,False,77.0,3,20.666667,3.725806,False
242549,242549,2008.0,336040,CSK,RR,RR,20,5,0.0,False,77.0,3,20.833333,3.696000,False

In [4]:
df.columns

Index(['Unnamed: 0', 'season', 'match_id', 'home_team', 'away_team',
       'current_innings', 'over', 'ball', 'wkt_batsman_runs', 'isRetiredHurt',
       'cumulative_runs', 'wickets_lost', 'overs_bowled', 'run_rate',
       'powerplay'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242550 entries, 0 to 242549
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        242550 non-null  int64
 1   season            242067 non-null  float64
 2   match_id          242550 non-null  int64
 3   home_team         242550 non-null  object
 4   away_team         242550 non-null  object
 5   current_innings   242550 non-null  object
 6   over              242550 non-null  int64
 7   ball              242550 non-null  int64
 8   wkt_batsman_runs  242550 non-null  float64
 9   isRetiredHurt     242550 non-null  bool
 10  cumulative_runs   242550 non-null  float64
 11  wickets_lost      242550 non-null  int64
 12  overs_bowled      242550 non-null  float64
 13  run_rate          242550 non-null  float64
 14  powerplay         242550 non-null  bool
dtypes: bool(2), float64(5), int64(5), object(3)
memory usage: 24.5+ MB

In [6]:
df.describe()

,Unnamed: 0,season,match_id,over,ball,wkt_batsman_runs,cumulative_runs,wickets_lost,overs_bowled,run_rate
count,242550.000000,242067.000000,2.425500e+05,242550.000000,242550.000000,242550.000000,242550.000000,242550.000000,242550.000000,242550.000000
mean,121274.500000,2015.588048,8.701769e+05,10.161678,3.483875,0.921571,37.952257,2.164465,10.742324,2.754477
std,70018.298233,4.639506,3.530671e+05,5.658053,1.707451,5.932493,40.754669,1.949695,5.661658,3.092077
min,0.000000,2008.000000,3.359820e+05,1.000000,1.000000,0.000000,0.000000,0.000000,1.166667,0.000000
25%,60637.250000,2012.000000,5.483150e+05,5.000000,2.000000,0.000000,1.000000,1.000000,5.833333,0.250000
50%,121274.500000,2015.000000,8.298190e+05,10.000000,3.000000,0.000000,25.000000,2.000000,10.666667,2.463158
75%,181911.750000,2020.000000,1.216506e+06,15.000000,5.000000,0.000000,61.000000,3.000000,15.500000,4.327869
max,242549.000000,2023.000000,1.370353e+06,20.000000,7.000000,129.000000,343.000000,14.000000,21.000000,147.428571

In [7]:
df.shape

(242550, 15)

In [8]:
new = df.filter(['overs_bowled', 'wickets_lost', 'run_rate', 'powerplay','cumulative_runs'], axis=1)

In [9]:
new

        overs_bowled  wickets_lost  run_rate  powerplay  cumulative_runs
0           1.166667             0  0.000000       True              0.0
1           1.333333             0  0.000000       True              0.0
2           1.500000             0  0.000000       True              0.0
3           1.666667             0  0.000000       True              0.0
4           1.833333             0  0.000000       True              0.0
...              ...           ...       ...        ...              ...
242545     20.333333             2  3.786885      False             77.0
242546     20.500000             3  3.756098      False             77.0
242547     20.666667             3  3.725806      False             77.0
242548     20.666667             3  3.725806      False             77.0
242549     20.833333             3  3.696000      False             77.0

[242550 rows x 5 columns]

In [10]:
ratio = 0.8
total_rows = new.shape[0]
train_size = int(total_rows*ratio)

In [11]:
train = new[0:train_size]
test = new[train_size:]

In [12]:
train

        overs_bowled  wickets_lost  run_rate  powerplay  cumulative_runs
0           1.166667             0  0.000000       True              0.0
1           1.333333             0  0.000000       True              0.0
2           1.500000             0  0.000000       True              0.0
3           1.666667             0  0.000000       True              0.0
4           1.833333             0  0.000000       True              0.0
...              ...           ...       ...        ...              ...
194035     18.833333             6  5.734513      False            108.0
194036     19.000000             6  5.684211      False            108.0
194037     19.166667             6  5.634783      False            108.0
194038     19.333333             6  5.586207      False            108.0
194039     19.500000             6  5.743590      False            112.0

[194040 rows x 5 columns]

In [13]:
test

        overs_bowled  wickets_lost  run_rate  powerplay  cumulative_runs
194040     19.666667             6  6.711864      False            132.0
194041     19.833333             6  6.655462      False            132.0
194042     20.000000             6  6.600000      False            132.0
194043     20.166667             6  6.545455      False            132.0
194044     20.333333             6  6.491803      False            132.0
...              ...           ...       ...        ...              ...
242545     20.333333             2  3.786885      False             77.0
242546     20.500000             3  3.756098      False             77.0
242547     20.666667             3  3.725806      False             77.0
242548     20.666667             3  3.725806      False             77.0
242549     20.833333             3  3.696000      False             77.0

[48510 rows x 5 columns]

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [15]:
y=new['cumulative_runs']
x=new.drop(columns=['cumulative_runs'])

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)

In [17]:
x_train

        overs_bowled  wickets_lost  run_rate  powerplay
75297       1.166667             1  0.000000       True
188346      7.666667             4  2.086957      False
135421     18.333333             4  5.618182      False
108174     18.000000             2  1.722222      False
100799     10.333333             1  2.612903      False
...              ...           ...       ...        ...
119879     10.833333             2  6.369231      False
103694     12.500000             2  0.480000      False
131932      6.000000             3  6.000000       True
146867     18.833333             2  4.725664      False
121958     10.833333             2  1.938462      False

[181912 rows x 4 columns]

In [18]:
x_test

        overs_bowled  wickets_lost  run_rate  powerplay
122566     10.666667             0  2.437500      False
147656      5.166667             1  0.000000       True
27099      20.833333             6  7.104000      False
42493       2.666667             0  0.000000       True
154359     19.000000             2  4.789474      False
...              ...           ...       ...        ...
92333       4.333333             3  6.000000       True
74059      16.500000             3  2.363636      False
111812     13.000000             3  2.692308      False
119204     18.500000             4  5.513514      False
115299     10.833333             1  2.123077      False

[60638 rows x 4 columns]

In [19]:
y_train

75297       0.0
188346     16.0
135421    103.0
108174     31.0
100799     27.0
          ...
119879     69.0
103694      6.0
131932     36.0
146867     89.0
121958     21.0
Name: cumulative_runs, Length: 181912, dtype: float64

In [20]:
y_test

122566     26.0
147656      0.0
27099     148.0
42493       0.0
154359     91.0
          ...
92333      26.0
74059      39.0
111812     35.0
119204    102.0
115299     23.0
Name: cumulative_runs, Length: 60638, dtype: float64

In [21]:
rf_model=RandomForestRegressor(n_estimators=200, max_depth=None, random_state=42,min_samples_leaf=1,min_samples_split=2)

In [22]:
rf_model

RandomForestRegressor(n_estimators=200, random_state=42)

In [23]:
rf_model.fit(x_train,y_train)
pred=rf_model.predict(x_test)

In [24]:
mse=mean_squared_error(y_test,pred)
rf_r2=r2_score(y_test,pred)

In [25]:
mse

0.15277755120551473

In [52]:
rf_r2

0.9999087152586794